app/MKF.Web/Models/JuradoViewModels.cs
using MKF.Web.Models.Comum;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace MKF.Web.Models
{
    public class JuradoViewModels
    {
        public List<JuradoModels> Jurados { get; set; }
        public JuradoModels Jurado { get; set; }
    }

    public class JuradoModels
    {
        public JuradoModels()
        {
            Usuario = new UsuarioModels { TipoAcesso = "J", DadosPessoais = new Comum.PessoaModels { Tipo = "J", Endereco = new EnderecoModels { Tipo = "R" } } };
            Contatos = new List<ContatoModels>();
        }

        public string Url { get; set; }
        public UsuarioModels Usuario { get; set; }
        public List<ContatoModels> Contatos { get; set; }
    }
}

app/MKF.Web/Areas/Administrador/Controllers/JuradosController.cs
using MKF.Web.Infra;
using MKF.Web.Infra.Servicos;
using MKF.Web.Models;
using MKF.Web.Models.Comum;
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Web;
using System.Web.Mvc;

namespace MKF.Web.Areas.Administrador.Controllers
{
    public class JuradosController : Controller
    {
        // GET: Administrador/Jurados
        public ActionResult Index()
        {
            List<PessoaModels> jurados = new List<PessoaModels>();

            var jurado = Comum.ListarPor<PessoaModels>(new PessoaModels { Tipo = "J" }, "Pessoa");

            if (!string.IsNullOrEmpty(jurado))
                jurados = JsonConvert.DeserializeObject<List<PessoaModels>>(jurado);

            return View(jurados);
        }

        // GET: Administrador/Jurados
        public ActionResult Create()
        {
            JuradoModels jurado = new JuradoModels();
            jurado.Usuario.DadosPessoais.Contatos = new List<ContatoModels>();
            jurado.Usuario.DadosPessoais.Contatos.Add(new ContatoModels { Tipo = "T" });
            jurado.Usuario.DadosPessoais.Contatos.Add(new ContatoModels { Tipo = "C" });
            jurado.Usuario.DadosPessoais.Contatos.Add(new ContatoModels { Tipo = "E" });
            return View(jurado);
        }

        [AcceptVerbs(HttpVerbs.Post)]
        [HttpPost]
        public ActionResult Create(JuradoModels model)
        {
            ContatoModels contE = model.Contatos.Where(m => m.Tipo.Equals("E")).FirstOrDefault();

            if (contE != null && !Funcoes.ValidarEmail(contE.Dado, true))
            {
                ModelState.AddModelError(string.Empty, "E-mail inválido ou não informado");
            }

            ContatoModels contT = model.Contatos.Where(m => m.Tipo.Equals("T")).FirstOrDefault();

            if (contT != null && !Funcoes.ValidarTelefone(contT.Dado, true))
            {
                ModelState.AddModelError(string.Empty, "Telefone inválido ou não informado");
            }

            ContatoModels contC = model.Contatos.Where(m => m.Tipo.Equals("C")).FirstOrDefault();

            if (contC != null && !Funcoes.ValidarTelefone(contC.Dado, true))
            {
                ModelState.AddModelError(string.Empty, "Celular inválido ou não informado");
            }


            if (!ModelState.IsValid)
            {
                var errorList = (from item in ModelState.Values
                                 from error in item.Errors
                                 select error.ErrorMessage).ToList();

                StringBuilder sb = new StringBuilder();

                foreach (var item in errorList)
                {
                    sb.AppendFormat("<p>{0}</p>", item);
                }

                return Json(new { Status = "Warning", Data = sb.ToString() }, JsonRequestBehavior.AllowGet);
            }

            int pessoa = 0;
            int usuario = 0;
            int endereco = 0;
            int contato = 0;

            if (!model.Usuario.DadosPessoais.Id.HasValue)
            {
                model.Usuario.DadosPessoais.Tipo = "J";
                pessoa = Comum.Gravar<PessoaModels>(model.Usuario.DadosPessoais, "Pessoa");
                if (pessoa > 0)
                {
                    model.Usuario.CodigoAcesso = "002";
                    model.Usuario.Status = 0;
                    model.Usuario.IdPessoa = pessoa;
                    model.Usuario.Password = Util.CriptografaSenha(model.Usuario.Password);
                    usuario = Comum.Gravar<UsuarioModels>(model.Usuario, "Usuario");
                    if (usuario > 0)
                    {
                        model.Usuario.DadosPessoais.Endereco.IdPessoa = pessoa;
                        endereco = Comum.Gravar<EnderecoModels>(model.Usuario.DadosPessoais.Endereco, "Endereco");
                        if (endereco > 0)
                        {
                            foreach (var item in model.Usuario.DadosPessoais.Contatos)
                            {
                                item.IdPessoa = pessoa;

                                contato = Comum.Gravar<ContatoModels>(item, "Contato");

                                if (contato == 0)
                                {
                                    Comum.Excluir(pessoa, "Pessoa");
                                    Comum.Excluir(usuario, "Usuario");
                                    Comum.Excluir(endereco, "Endereco");
                                    return Json(new { Status = "Error", Data = "Falha ao gravar o Contato. Favor entre em contato junto ao administrador do sistema!" }, JsonRequestBehavior.AllowGet);
                                }
                            }

                            return Json(new { Status = "Success" }, JsonRequestBehavior.AllowGet);
                        }
                        else
                        {
                            Comum.Excluir(pessoa, "Pessoa");
                            Comum.Excluir(usuario, "Usuario");
                            return Json(new { Status = "Error", Data = "Falha ao gravar o Endereço. Favor entre em contato junto ao administrador do sistema!" }, JsonRequestBehavior.AllowGet);
                        }
                    }
                    else
                    {
                        Comum.Excluir(pessoa, "Pessoa");
                        return Json(new { Status = "Error", Data = "Falha ao criar o Usuário do jurado. Favor entre em contato junto ao administrador do sistema!" }, JsonRequestBehavior.AllowGet);
                    }
                }
                else
                    return Json(new { Status = "Error", Data = "Falha ao gravar o Jurado. Favor entre em contato junto ao administrador do sistema!" }, JsonRequestBehavior.AllowGet);
            }
            else
            {
                model.Usuario.DadosPessoais.Tipo = "J";
                if (Comum.Alterar<PessoaModels>(model.Usuario.DadosPessoais, "Pessoa"))
                {
                    model.Usuario.Password = string.IsNullOrEmpty(model.Usuario.Senha) ? model.Usuario.Password : Util.CriptografaSenha(model.Usuario.Senha);
                    if (Comum.Alterar<UsuarioModels>(model.Usuario, "Usuario"))
                    {
                        if (Comum.Alterar<EnderecoModels>(model.Usuario.DadosPessoais.Endereco, "Endereco"))
                        {
                            foreach (var item in model.Contatos)
                            {
                                if (item.Id == 0)
                                {
                                    item.IdPessoa = model.Usuario.DadosPessoais.Id.Value;
                                    contato = Comum.Gravar<ContatoModels>(item, "Contato");

                                    if (contato == 0)
                                        return Json(new { Status = "Error", Data = "Falha ao gravar o novo Contato. Favor entre em contato junto ao administrador do sistema!" }, JsonRequestBehavior.AllowGet);
                                }
                                else if (!Comum.Alterar<ContatoModels>(item, "Contato"))
                                    return Json(new { Status = "Error", Data = "Falha ao alterar o Contato. Favor entre em contato junto ao administrador do sistema!" }, JsonRequestBehavior.AllowGet);
                            }

                            return Json(new { Status = "Success" }, JsonRequestBehavior.AllowGet);
                        }
                        else
                            return Json(new { Status = "Error", Data = "Falha ao alterar o Endereço. Favor entre em contato junto ao administrador do sistema!" }, JsonRequestBehavior.AllowGet);
                    }
                    else
                        return Json(new { Status = "Error", Data = "Falha ao alterar o Usuário. Favor entre em contato junto ao administrador do sistema!" }, JsonRequestBehavior.AllowGet);
                }
                else
                    return Json(new { Status = "Error", Data = "Falha ao alterar o Jurado. Favor entre em contato junto ao administrador do sistema!" }, JsonRequestBehavior.AllowGet);
            }
        }

        [HttpPost, ActionName("Delete")]
        public virtual JsonResult Delete(int id)
        {
            var domainObj = Comum.Excluir(id, "Pessoa");

            return Json("");
        }

        public ActionResult Edit(int id, string url)
        {
            return View("Create", PreencherModels(id, url));
        }

        private JuradoModels PreencherModels(int id, string url)
        {
            JuradoModels jurado = new JuradoModels { Url = url };

            var ev = UsuarioSrv.BuscarJurado(id);

            jurado.Usuario = JsonConvert.DeserializeObject<UsuarioModels>(ev.Result);

            return jurado;
        }
    }
}

app/MKF.Web/Areas/Jurados/Controllers/SeletivaController.cs
using MKF.Web.Infra;
using MKF.Web.Infra.Servicos;
using MKF.Web.Models;
using MKF.Web.Models.Comum;
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MKF.Web.Areas.Jurados.Controllers
{
    public class SeletivaController : Controller
    {
        // GET: Administrador/Seletiva
        public ActionResult Index()
        {
            var t = Util.RecuperarIdPessoa();
            List<SeletivaViewModels> seletivas = new List<SeletivaViewModels>();

            var ev = RelJuradosSeletiva.ListarSeletivasJurado(t.Value);

            seletivas = JsonConvert.DeserializeObject<List<SeletivaViewModels>>(ev.Result);

            return View(seletivas);
        }

        public ActionResult Modelos(int idSeletiva)
        {
            ViewBag.IdSeletiva = idSeletiva;
            return View();
        }

        public ActionResult Avaliar(string id)
        {
            var ids = id.Split(',');
            ModeloSeletivaModels inscrito = new ModeloSeletivaModels();
            var c = InscricaoSeletivaSrv.RecuperarInscrito(int.Parse(ids[0]));

            if (!string.IsNullOrEmpty(c.Result))
                inscrito = JsonConvert.DeserializeObject<ModeloSeletivaModels>(c.Result);

            if (inscrito.Id > 0)
            {
                var reps1 = PessoaSrv.BuscarPessoa(inscrito.IdMae);
                inscrito.Responsavel1 = JsonConvert.DeserializeObject<PessoaModels>(reps1.Result);

                if (inscrito.IdPai > 0)
                {
                    var reps2 = PessoaSrv.BuscarPessoa(inscrito.IdPai);
                    inscrito.Responsavel2 = JsonConvert.DeserializeObject<PessoaModels>(reps2.Result);
                }

                inscrito.Idade = Util.CalculateIdade(inscrito.Crianca.DataNascimento.Value);

                inscrito.Pagamento = inscrito.Pagamentos.FirstOrDefault(p => p.Id.Value == int.Parse(ids[1]));

                if (inscrito.Pagamento != null)
                {
                    var sel = Comum.ListarPorIdUnion(inscrito.Pagamento.IdSeletiva.Value, "Seletiva", "BuscarSeletiva");
                    inscrito.Seletiva = JsonConvert.DeserializeObject<SeletivaViewModels>(sel.Result);
                }
                else
                {
                    inscrito.Pagamento = new PagamentoViewModels();

                    var sel = Comum.Listar(string.Empty, "Seletiva");
                    List<SeletivaViewModels> lstSeletiva = JsonConvert.DeserializeObject<List<SeletivaViewModels>>(sel.Result);

                    inscrito.Seletiva = lstSeletiva.Count() > 0 ? lstSeletiva.FirstOrDefault(a => a.Status == 0) : new Models.SeletivaViewModels();
                }

                var img = Comum.ListarPor(new ImagemModels { IdPessoa = inscrito.IdCrianca }, "Imagem");

                inscrito.Crianca.Imagens = JsonConvert.DeserializeObject<List<ImagemModels>>(img);

                if (inscrito.Crianca.Imagens.Count() > 0)
                    inscrito.UrlImagem = inscrito.Crianca.Imagens[0].URL;

                if (inscrito.Manequim == null)
                    inscrito.Manequim = new ManequimViewModels { IdModelo = inscrito.IdModelo };
            }

            if (string.IsNullOrEmpty(inscrito.Inscricao))
                inscrito.Inscricao = string.Format("S{0}{1}{2}{3}", inscrito.Id, inscrito.IdCrianca, inscrito.IdMae, inscrito.IdPai);

            var avJurado = AvaliacaoSrv.ListarAvaliacaoJuradoModelo(inscrito.Id, Util.RecuperarIdPessoa().Value);

            inscrito.Avaliacoes = JsonConvert.DeserializeObject<List<AvaliacaoModel>>(avJurado.Result);

            return View(inscrito);
        }

        [HttpPost]
        public JsonResult SalvarAvaliacao(string id, string resultado, string total, string media)
        {
            string[] notas = resultado.Split(';');
            var i = 0;
            AvaliacaoSrv.DeletarJuradosSeletiva(int.Parse(id), Util.RecuperarIdPessoa().Value);
            foreach (string item in notas)
            {
                if (!string.IsNullOrEmpty(item))
                {
                    string[] itemava = item.Split('-');
                    AvaliacaoModel avaliacao = new Models.AvaliacaoModel
                    {
                        DataAvaliacao = TimeZoneInfo.ConvertTime(DateTime.Now, TimeZoneInfo.FindSystemTimeZoneById("E. South America Standard Time")),
                        IdModelo = int.Parse(id),
                        Item = itemava[0],
                        Nota = int.Parse(itemava[1]),
                        IdJurado = Util.RecuperarIdPessoa().Value
                    };

                    i = Comum.Gravar<AvaliacaoModel>(avaliacao, "Avaliacao");

                    if (i == 0) break;
                }
            }

            if (i > 0)
            {
                ModeloViewModels model = new Models.ModeloViewModels();

                var c = Comum.ListarPorId(int.Parse(id), "Modelo");

                if (!string.IsNullOrEmpty(c.Result))
                {
                    model = JsonConvert.DeserializeObject<ModeloViewModels>(c.Result);
                    model.Status = 1;
                    model.Avaliacao = int.Parse(total);
                    model.MediaAvaliacao = decimal.Parse(media.Replace('.', ','));
                    if (Comum.Alterar<ModeloViewModels>(model, "Modelo"))
                        return Json(new { Status = "Success" }, JsonRequestBehavior.AllowGet);
                    else
                    {
                        AvaliacaoSrv.DeletarJuradosSeletiva(int.Parse(id), Util.RecuperarIdPessoa().Value);
                        return Json(new { Status = "Error", Data = "Falha ao avaliar a criança. Favor entre em contato junto ao administrador do sistema!" }, JsonRequestBehavior.AllowGet);
                    }
                }
                else
                {
                    AvaliacaoSrv.DeletarJuradosSeletiva(int.Parse(id), Util.RecuperarIdPessoa().Value);
                    return Json(new { Status = "Error", Data = "Falha ao avaliar a criança. Favor entre em contato junto ao administrador do sistema!" }, JsonRequestBehavior.AllowGet);
                }
            }
            else
                return Json(new { Status = "Error", Data = "Falha ao avaliar a criança. Favor entre em contato junto ao administrador do sistema!" }, JsonRequestBehavior.AllowGet);
        }
    }
}

app/MKF.Web/Areas/Administrador/Views/Jurados/Create.cshtml
@model MKF.Web.Models.JuradoModels

@{
    ViewBag.Title = "Create";
    Layout = "~/Areas/Administrador/Views/Shared/_Layout.cshtml";
}

<div class="breadcrumbs ace-save-state" id="breadcrumbs">
    <ul class="breadcrumb">
        <li>
            <i class="ace-icon fa fa-home home-icon"></i>
            <a href="#">Home</a>
        </li>

        <li>
            <a href="#">Administrativo</a>
        </li>
        <li class="active">Jurados</li>
    </ul>
</div>

<!-- /section:basics/content.breadcrumbs -->
<div class="page-content">
    <div class="page-header">
        <h1>
            Cadastrar Jurados
        </h1>
    </div><!-- /.page-header -->

    <div class="row">
        <div class="col-xs-12 col-md-12">
            @{using (Html.BeginForm("Create", "Jurados", FormMethod.Post, new { @class = "form-horizontal", @id = "basic_validate" }))
                {
                    @Html.HiddenFor(m => m.Usuario.Id)
                    @Html.HiddenFor(m => m.Usuario.IdPessoa)
                    @Html.HiddenFor(m => m.Usuario.Status)
                    @Html.HiddenFor(m => m.Usuario.DadosPessoais.Id)
                    @Html.HiddenFor(m => m.Usuario.DadosPessoais.Status)
                    @Html.HiddenFor(m => m.Usuario.DadosPessoais.Tipo)
                    @Html.HiddenFor(m => m.Usuario.DadosPessoais.Endereco.Id)
                    @Html.HiddenFor(m => m.Usuario.DadosPessoais.Endereco.IdPessoa)
                    @Html.HiddenFor(m => m.Usuario.DadosPessoais.Endereco.Tipo)
                    @Html.HiddenFor(m => m.Usuario.DadosPessoais.Contatos[0].Id)
                    @Html.HiddenFor(m => m.Usuario.DadosPessoais.Contatos[0].IdPessoa)
                    @Html.HiddenFor(m => m.Usuario.DadosPessoais.Contatos[1].Id)
                    @Html.HiddenFor(m => m.Usuario.DadosPessoais.Contatos[1].IdPessoa)
                    @Html.HiddenFor(m => m.Usuario.DadosPessoais.Contatos[2].Id)
                    @Html.HiddenFor(m => m.Usuario.DadosPessoais.Contatos[2].IdPessoa)
                    @Html.HiddenFor(m => m.Url)
                    @Html.AntiForgeryToken()
                    <div class="row">
                        <div class="col-sm-6">
                            <label for="form-field-1"> Nome <span class="text-danger"> * </span></label>

                            <div class="row">
                                <div class="col-xs-12 col-sm-12">
                                    @Html.TextBoxFor(m => m.Usuario.DadosPessoais.Nome, new { @class = "col-xs-12 col-sm-12", @placeholder = "Nome" })
                                </div>
                            </div>
                        </div>
                        <div class="col-md-2">
                            <label for="form-field-1"> CPF <span class="text-danger"> * </span></label>

                            <div class="row">
                                <div class="col-xs-12 col-sm-12">
                                    @Html.TextBoxFor(m => m.Usuario.DadosPessoais.Cpf, new { @class = "col-xs-12 col-sm-12", @placeholder = "CPF" })
                                </div>
                            </div>
                        </div>
                        <div class="col-md-2">
                            <label for="form-field-1"> Usuário <span class="text-danger"> * </span></label>

                            <div class="row">
                                <div class="col-xs-12 col-sm-12">
                                    @Html.TextBoxFor(m => m.Usuario.User, new { @class = "col-xs-12 col-sm-12", @placeholder = "Usuário" })
                                </div>
                            </div>
                        </div>
                        @if (!Model.Usuario.Id.HasValue)
                        {
                            <div class="col-md-2">
                                <label for="form-field-1"> Senha <span class="text-danger"> * </span></label>

                                <div class="row">
                                    <div class="col-xs-12 col-sm-12">
                                        @Html.TextBoxFor(m => m.Usuario.Password, new { @class = "col-xs-12 col-sm-12", @placeholder = "Senha", @type = "password" })
                                    </div>
                                </div>
                            </div>
                        }
                        else
                        {
                            @Html.HiddenFor(m => m.Usuario.Password)
                            <div class="col-md-2">
                                <label for="form-field-1"> Senha <span class="text-danger"> * </span></label>

                                <div class="row">
                                    <div class="col-xs-12 col-sm-12">
                                        @Html.TextBoxFor(m => m.Usuario.Senha, new { @class = "col-xs-12 col-sm-12", @placeholder = "Senha", @type = "password" })
                                    </div>
                                </div>
                            </div>
                        }
                    </div>
                    <h3 class="header blue lighter smaller">
                        <i class="ace-icon fa fa-list-alt smaller-90"></i>
                        Endereço
                    </h3>
                    <div class="row">
                        <div class="col-md-2">
                            <label for="form-field-1"> Cep <span class="text-danger"> * </span></label>

                            <div class="row">
                                <div class="col-xs-12 col-sm-12">
                                    @Html.TextBoxFor(m => m.Usuario.DadosPessoais.Endereco.Cep, new { @class = "col-xs-12 col-sm-12 cep", @placeholder = "Cep" })
                                </div>
                            </div>
                        </div>
                        <div class="col-md-4">
                            <label for="form-field-1"> Logradouro <span class="text-danger"> * </span></label>

                            <div class="row">
                                <div class="col-xs-12 col-sm-12">
                                    @Html.TextBoxFor(m => m.Usuario.DadosPessoais.Endereco.Logradouro, new { @class = "col-xs-12 col-sm-12", @placeholder = "Logradouro" })
                                </div>
                            </div>
                        </div>
                        <div class="col-md-2">
                            <label for="form-field-1"> Número <span class="text-danger"> * </span></label>

                            <div class="row">
                                <div class="col-xs-12 col-sm-12">
                                    @Html.TextBoxFor(m => m.Usuario.DadosPessoais.Endereco.Numero, new { @class = "col-xs-12 col-sm-12", @placeholder = "Número" })
                                </div>
                            </div>
                        </div>
                        <div class="col-md-4">
                            <label for="form-field-1"> Complemento <span class="text-danger"> * </span></label>

                            <div class="row">
                                <div class="col-xs-12 col-sm-12">
                                    @Html.TextBoxFor(m => m.Usuario.DadosPessoais.Endereco.Complemento, new { @class = "col-xs-12 col-sm-12", @placeholder = "Complemento" })
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="space-12"></div>
                    <div class="row">
                        <div class="col-md-4">
                            <label for="form-field-1"> Bairro <span class="text-danger"> * </span></label>

                            <div class="row">
                                <div class="col-xs-12 col-sm-12">
                                    @Html.TextBoxFor(m => m.Usuario.DadosPessoais.Endereco.Bairro, new { @class = "col-xs-12 col-sm-12", @placeholder = "Bairro" })
                                </div>
                            </div>
                        </div>
                        <div class="col-md-4">
                            <label for="form-field-1"> Cidade <span class="text-danger"> * </span></label>

                            <div class="row">
                                <div class="col-xs-12 col-sm-12">
                                    @Html.TextBoxFor(m => m.Usuario.DadosPessoais.Endereco.Cidade, new { @class = "col-xs-12 col-sm-12", @placeholder = "Cidade" })
                                </div>
                            </div>
                        </div>
                        <div class="col-sm-4">
                            <label for="form-field-1"> Estado <span class="text-danger"> * </span></label>

                            <div class="row">
                                <div class="col-xs-12 col-sm-12">
                                    @Html.DropDownListFor(m => m.Usuario.DadosPessoais.Endereco.Estado, MKF.Web.Infra.Funcoes.Ufs(Model.Usuario.DadosPessoais.Endereco.Estado), "Selecione", new { @class = "col-xs-12 col-sm-12" })
                                </div>
                            </div>
                        </div>
                    </div>
                    <h3 class="header blue lighter smaller">
                        <i class="ace-icon fa fa-list-alt smaller-90"></i>
                        Contatos
                    </h3>
                    <div class="row">
                        <div class="col-md-3">
                            <label for="form-field-1"> Telefone <span class="text-danger"> * </span></label>
                            @Html.HiddenFor(m => m.Usuario.DadosPessoais.Contatos[0].Tipo)
                            <div class="row">
                                <div class="col-xs-12 col-sm-12">
                                    @Html.TextBoxFor(m => m.Usuario.DadosPessoais.Contatos[0].Dado, new { @class = "col-xs-12 col-sm-12 fone", @placeholder = "Telefone" })
                                </div>
                            </div>
                        </div>
                        <div class="col-md-3">
                            <label for="form-field-1"> Celular <span class="text-danger"> * </span></label>
                            @Html.HiddenFor(m => m.Usuario.DadosPessoais.Contatos[1].Tipo)
                            <div class="row">
                                <div class="col-xs-12 col-sm-12">
                                    @Html.TextBoxFor(m => m.Usuario.DadosPessoais.Contatos[1].Dado, new { @class = "col-xs-12 col-sm-12 fone", @placeholder = "Celular" })
                                </div>
                            </div>
                        </div>
                        <div class="col-md-6">
                            <label for="form-field-1"> E-mail <span class="text-danger"> * </span></label>
                            @Html.HiddenFor(m => m.Usuario.DadosPessoais.Contatos[2].Tipo)
                            <div class="row">
                                <div class="col-xs-12 col-sm-12">
                                    @Html.TextBoxFor(m => m.Usuario.DadosPessoais.Contatos[2].Dado, new { @class = "col-xs-12 col-sm-12", @placeholder = "E-mail" })
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="clearfix form-actions">
                        <div class="col-md-offset-3 col-md-9">
                            <a href="@Url.Action("Index", "Jurados")" class="btn btn-info" data-original-title="Novo">
                                <i class="ace-icon fa fa-reply bigger-110"></i> Voltar
                            </a>

                            <button type="button" class="btn btn-success" id="btnSalvar">
                                <i class="ace-icon fa fa-check"></i> Salvar
                            </button>
                        </div>
                    </div>

                }
            }
        </div>
    </div>
</div>
<script type="text/javascript">
    var urlIndex = '@Url.Action("Index", "Jurados")';
    var urlCreate = '@Url.Action("Create", "Jurados")';
</script>

<script src="~/Contents/assets/pages/Mensagem.js"></script>
<script src="~/Contents/assets/pages/Jurado/AdmJurado.js"></script>