app/MKF.Web/Models/GrifesViewModels.cs
using MKF.Web.Models.Comum;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace MKF.Web.Models
{
    public class GrifesViewModels
    {
        public List<GrifeModel> Grifes { get; set; }
    }

    public class GrifeModel
    {
        public GrifeModel()
        {
            Empresa = new Comum.EmpresaModels { Tipo = "L" };
            Enderecos = new List<EnderecoModels>();
            Enderecos.Add(new EnderecoModels { });
            Contatos = new List<ContatoModels>();
            Contatos.Add(new ContatoModels());
            Socios = new List<ResponsavelModels>();
            Socios.Add(new Comum.ResponsavelModels { });
            Imagens = new List<ImagemModels>();
            Imagens.Add(new Comum.ImagemModels { });
            RedesSociais = new List<RedeSocialModels>();
            RedesSociais.Add(new Comum.RedeSocialModels { });

        }

        public EmpresaModels Empresa { get; set; }
        public List<EnderecoModels> Enderecos { get; set; }
        public virtual List<ContatoModels> Contatos { get; set; }
        public virtual List<ResponsavelModels> Socios { get; set; }
        public virtual List<ImagemModels> Imagens { get; set; }
        public virtual List<RedeSocialModels> RedesSociais { get; set; }
        //public virtual List<Modelo> Criancas { get; set; }
    }
}

app/MKF.Web/Areas/Administrador/Controllers/GrifeController.cs
using MKF.Web.Models;
using MKF.Web.Models.Comum;
using Newtonsoft.Json;
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;

namespace MKF.Web.Areas.Administrador.Controllers
{
    public class GrifeController : Controller
    {
        // GET: Administrador/Grife
        public ActionResult Index()
        {
            GrifesViewModels grifes = new GrifesViewModels { Grifes = new List<GrifeModel>() };
            return View(grifes);
        }

        [AcceptVerbs(HttpVerbs.Get)]
        public ActionResult Create()
        {
            GrifeModel lj = new GrifeModel();
            return View(lj);
        }

        [AcceptVerbs(HttpVerbs.Post)]
        [HttpPost]
        public ActionResult Create(GrifeModel model)
        {
            if (!ModelState.IsValid)
            {
                return PartialView("~/Areas/Administrador/Views/Grife/Partial/_dadosLoja.cshtml", model);
            }

            return PartialView(model);
        }

        [AcceptVerbs(HttpVerbs.Post)]
        [HttpPost]
        public ActionResult Step1(EmpresaModels model)
        {
            if (!ModelState.IsValid)
            {
                return PartialView("~/Areas/Administrador/Views/Grife/Partial/_dadosLoja.cshtml", model);
            }

            GrifeModel l = new GrifeModel { Empresa = model };

            var j = JsonConvert.SerializeObject(l);

            return Json(new { Status = "Success", Data = j }, JsonRequestBehavior.AllowGet);
        }

        [AcceptVerbs(HttpVerbs.Post)]
        [HttpPost]
        public ActionResult Step2(List<EnderecoModels> model)
        {
            if (!ModelState.IsValid)
            {
                return PartialView("~/Areas/Administrador/Views/Grife/Partial/_endereco.cshtml", model);
            }

            return Json(new { Status = "Success" }, JsonRequestBehavior.AllowGet);
        }


        [AcceptVerbs(HttpVerbs.Get)]
        [HttpGet]
        public ActionResult Step2Voltar(string json)
        {
            GrifeModel l = JsonConvert.DeserializeObject<GrifeModel>(json);

            return PartialView("~/Areas/Administrador/Views/Grife/Partial/_endereco.cshtml", l.Enderecos.Where(e => e.Cep != null).ToList());

        }
        [AcceptVerbs(HttpVerbs.Post)]
        [HttpPost]
        public ActionResult Step3(List<ResponsavelModels> model)
        {
            if (!ModelState.IsValid)
            {
                return PartialView("~/Areas/Administrador/Views/Grife/Partial/_responsaveisLoja.cshtml", model);
            }

            return Json(new { Status = "Success" }, JsonRequestBehavior.AllowGet);
        }

        [AcceptVerbs(HttpVerbs.Post)]
        [HttpPost]
        public ActionResult Step4(List<ImagemModels> model)
        {
            if (!ModelState.IsValid)
            {
                return PartialView("~/Areas/Administrador/Views/Grife/Partial/_imagens.cshtml", model);
            }

            return PartialView("~/Areas/Administrador/Views/Grife/Partial/_imagens.cshtml", model);
        }

        [AcceptVerbs(HttpVerbs.Post)]
        [HttpPost]
        public ActionResult NovoEndereco(List<EnderecoModels> model)
        {
            if (model == null)
                model = new List<EnderecoModels>();

            model.Add(new EnderecoModels());
            return PartialView("~/Areas/Administrador/Views/Grife/Partial/_endereco.cshtml", model);
        }

        [AcceptVerbs(HttpVerbs.Post)]
        [HttpPost]
        public ActionResult RemoverEndereco(List<EnderecoModels> model)
        {
            return PartialView("~/Areas/Administrador/Views/Grife/Partial/_endereco.cshtml", model.Where(m => m != null).ToList());
        }

        [AcceptVerbs(HttpVerbs.Post)]
        [HttpPost]
        public ActionResult NovoResponsavel(List<ResponsavelModels> model)
        {
            model.Add(new ResponsavelModels());
            return PartialView("~/Areas/Administrador/Views/Grife/Partial/_responsaveisLoja.cshtml", model);
        }

        [AcceptVerbs(HttpVerbs.Post)]
        [HttpPost]
        public ActionResult RemoverResponsavel(List<ResponsavelModels> model)
        {
            return PartialView("~/Areas/Administrador/Views/Grife/Partial/_responsaveisLoja.cshtml", model.Where(m => m != null).ToList());
        }

        [AcceptVerbs(HttpVerbs.Post)]
        [HttpPost]
        public ActionResult NovaImagem(List<ImagemModels> model)
        {
            model.Add(new ImagemModels());
            return PartialView("~/Areas/Administrador/Views/Grife/Partial/_imagens.cshtml", model);
        }

        [AcceptVerbs(HttpVerbs.Post)]
        [HttpPost]
        public ActionResult RemoverImagem(List<ImagemModels> model)
        {
            return PartialView("~/Areas/Administrador/Views/Grife/Partial/_imagens.cshtml", model.Where(m => m != null).ToList());
        }
    }
}

app/MKF.Web/Areas/Administrador/Views/Grife/Create.cshtml
@model MKF.Web.Models.GrifeModel

@{
    ViewBag.Title = "Create";
    Layout = "~/Areas/Administrador/Views/Shared/_Layout.cshtml";

    <link href="~/Content/global/plugins/fancybox/source/jquery.fancybox.css" rel="stylesheet" type="text/css" />
    <link href="~/Content/global/plugins/jquery-file-upload/blueimp-gallery/blueimp-gallery.min.css" rel="stylesheet" type="text/css" />
    <link href="~/Content/global/plugins/jquery-file-upload/css/jquery.fileupload.css" rel="stylesheet" type="text/css" />
    <link href="~/Content/global/plugins/jquery-file-upload/css/jquery.fileupload-ui.css" rel="stylesheet" type="text/css" />
}

<div class="page-bar">
    <ul class="page-breadcrumb">
        <li>
            <a href="index.html">Administrativo</a>
            <i class="fa fa-circle"></i>
        </li>
        <li>
            <a href="#">Grife</a>
            <i class="fa fa-circle"></i>
        </li>
        <li>
            <span>Cadastro</span>
        </li>
    </ul>
</div>
<!-- END PAGE BAR -->
<!-- END PAGE HEADER-->
<div class="row">
    <div class="col-md-12">
        <div class="portlet light" id="form_wizard_1">
            <div class="portlet-body">
                @{using (Html.BeginForm("Create", "Grife", FormMethod.Post, new { @class = "form-horizontal", @id = "basic_validate" }))
                    {
                        @Html.AntiForgeryToken()
                        @Html.HiddenFor(m => m.Empresa.Tipo)
                        @Html.Hidden("JsonForm", "")
                        <div class="form-wizard">
                            <div class="form-body">
                                <ul class="nav nav-pills nav-justified steps">
                                    <li class="active">
                                        <a href="#tab1" data-toggle="tab" class="step">
                                            <span class="number"> 1 </span>
                                            <span class="desc">
                                                <i class="fa fa-check"></i> Cadastral
                                            </span>
                                        </a>
                                    </li>
                                    <li>
                                        <a href="#tab2" data-toggle="tab" class="step">
                                            <span class="number"> 2 </span>
                                            <span class="desc">
                                                <i class="fa fa-check"></i> Endereço
                                            </span>
                                        </a>
                                    </li>
                                    <li>
                                        <a href="#tab3" data-toggle="tab" class="step">
                                            <span class="number"> 3 </span>
                                            <span class="desc">
                                                <i class="fa fa-check"></i> Responsáveis
                                            </span>
                                        </a>
                                    </li>
                                    <li>
                                        <a href="#tab4" data-toggle="tab" class="step">
                                            <span class="number"> 4 </span>
                                            <span class="desc">
                                                <i class="fa fa-check"></i> Imagens
                                            </span>
                                        </a>
                                    </li>
                                    <li>
                                        <a href="#tab5" data-toggle="tab" class="step">
                                            <span class="number"> 5 </span>
                                            <span class="desc">
                                                <i class="fa fa-check"></i> Confirmação
                                            </span>
                                        </a>
                                    </li>
                                </ul>
                                <div id="bar" class="progress progress-striped" role="progressbar">
                                    <div class="progress-bar progress-bar-success"> </div>
                                </div>
                                <div class="tab-content">
                                    <div class="alert alert-danger display-none">
                                        <button class="close" data-dismiss="alert"></button> Atenção.
                                    </div>
                                    <div class="alert alert-success display-none">
                                        <button class="close" data-dismiss="alert"></button> Cadastro realizado com sucesso!
                                    </div>
                                    <div id="step1" class="tab-pane active">
                                        <h3 class="block">Informe os dados abaixo</h3>
                                        @Html.Partial("~/Areas/Administrador/Views/Grife/Partial/_dadosLoja.cshtml", Model.Empresa)
                                        <div class="form-actions">
                                            <div class="row">
                                                <div class="col-md-offset-3 col-md-9">
                                                    @Html.ActionLink("Voltar", "Index", "Grife", new { @class = "btn btn-outline green" })
                                                    <input id="btnContinueDados" value="Continue" class="btn btn-outline green">
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                    <div id="step2" class="tab-pane">
                                        <h3 class="block">Informe os dados abaixo</h3>
                                        @Html.Partial("~/Areas/Administrador/Views/Grife/Partial/_endereco.cshtml", Model.Enderecos)
                                        <div class="form-actions">
                                            <div class="row">
                                                <div class="col-md-offset-3 col-md-9">
                                                    <input id="btnNovoEndereco" value="Novo" class="btn btn-success">
                                                </div>
                                            </div>
                                        </div>
                                        <div class="form-actions">
                                            <div class="row">
                                                <div class="col-md-offset-3 col-md-9">
                                                    <input id="btnVoltarEndereco" value="Voltar" class="btn btn-outline green">
                                                    <input id="btnContinueEndereco" value="Continue" class="btn btn-outline green">
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                    <div id="step3" class="tab-pane">
                                        <h3 class="block">Informe os dados abaixo</h3>
                                        @Html.Partial("~/Areas/Administrador/Views/Grife/Partial/_responsaveisLoja.cshtml", Model.Socios)
                                        <div class="form-actions">
                                            <div class="row">
                                                <div class="col-md-offset-3 col-md-9">
                                                    <input id="btnNovoResponsavel" value="Novo" class="btn btn-success">
                                                </div>
                                            </div>
                                        </div>
                                        <div class="form-actions">
                                            <div class="row">
                                                <div class="col-md-offset-3 col-md-9">
                                                    <input id="btnVoltarResponsavel" value="Voltar" class="btn btn-outline green">
                                                    <input id="btnContinueResponsavel" value="Continue" class="btn btn-outline green">
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                    <div id="step4" class="tab-pane">
                                        <h3 class="block">Informe os dados abaixo</h3>
                                        @Html.Partial("~/Areas/Administrador/Views/Grife/Partial/_imagens.cshtml", Model.Imagens)
                                        <div class="form-actions">
                                            <div class="row">
                                                <div class="col-md-offset-3 col-md-9">
                                                    <input id="btnNovaImagem" value="Nova" class="btn btn-success">
                                                </div>
                                            </div>
                                        </div>
                                        <div class="form-actions">
                                            <div class="row">
                                                <div class="col-md-offset-3 col-md-9">
                                                    <input id="btnVoltarImagem" value="Voltar" class="btn btn-outline green">
                                                    <input type="submit" id="btnFinalizarCadastro" value="Sim" class="btn btn-outline green">
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                    <div class="tab-pane">
                                        <h3 class="block">Cadastro realizado com sucesso!</h3>

                                        <div class="form-actions">
                                            <div class="row">
                                                <div class="col-md-offset-3 col-md-9">
                                                    @Html.ActionLink("Não", "Index", "Grife", new { @class = "btn btn-outline green" })
                                                    <input type="submit" id="btnFinalizarCadastro" value="Sim" class="btn btn-outline green">
                                                </div>
                                            </div>
                                        </div>

                                    </div>
                                </div>
                            </div>
                        </div>
                    }
                }
            </div>
        </div>
    </div>
</div>

<script src="~/Content/pages/scripts/Grife/AdmGrife.js" type="text/javascript"></script>

app/MKF.Web/Areas/Administrador/Views/Grife/Index.cshtml
@model MKF.Web.Models.GrifesViewModels
@{
    ViewBag.Title = "Index";
    Layout = "~/Areas/Administrador/Views/Shared/_Layout.cshtml";

    <link href="~/Content/global/plugins/datatables/datatables.min.css" rel="stylesheet" type="text/css" />
    <link href="~/Content/global/plugins/datatables/plugins/bootstrap/datatables.bootstrap.css" rel="stylesheet" type="text/css" />
}

<div class="page-bar">
    <ul class="page-breadcrumb">
        <li>
            <a href="index.html">Home</a>
            <i class="fa fa-circle"></i>
        </li>
        <li>
            <a href="#">Adminstrativo</a>
            <i class="fa fa-circle"></i>
        </li>
        <li>
            <span>Grifes</span>
        </li>
    </ul>
</div>
<div class="row">
    <div class="col-md-12">
        <!-- BEGIN EXAMPLE TABLE PORTLET-->
        <div class="portlet light bordered">
            <div class="portlet-title">
                <div class="caption font-dark">
                    <i class="icon-settings font-dark"></i>
                    <span class="caption-subject bold uppercase"> Grifes</span>
                </div>
            </div>
            <div class="portlet-body">
                <div class="table-toolbar">
                    <div class="row">
                        <div class="col-md-6">
                            <div class="btn-group">
                                <a href="@Url.Action("Create", "Grife")" class="btn sbold green" data-original-title="Editar">
                                    <i class="fa fa-plus"></i> Novo
                                </a>
                            </div>
                        </div>
                    </div>
                </div>
                <table class="table table-striped table-bordered table-hover table-checkable order-column" id="sample_1">
                    <thead>
                        <tr>
                            <th> Nome </th>
                            <th> Responsável </th>
                            <th> CNPJ  </th>
                            <th> Status </th>
                            <th> Ações </th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (var item in Model.Grifes)
                        {
                            <tr class="odd gradeX">
                                <td> @item.Empresa.NomeFantasia </td>
                                    <td>
                                        @item.Empresa.CNPJ
                                    </td>
                                    <td> @item.Empresa.RazaoSocial </td>
                                    <td>
                                        <span class="label label-sm label-success"> Ativo </span>
                                    </td>

                                    <td>
                                        <div class="btn-group">
                                            <button class="btn btn-xs green dropdown-toggle" type="button" data-toggle="dropdown" aria-expanded="false">
                                                Ação
                                                <i class="fa fa-angle-down"></i>
                                            </button>
                                            <ul class="dropdown-menu pull-left" role="menu">
                                                <li>
                                                    <a href="javascript:;">
                                                        <i class="icon-docs"></i> Editar
                                                    </a>
                                                </li>
                                                <li>
                                                    <a href="javascript:;">
                                                        <i class="icon-tag"></i> Excluir
                                                    </a>
                                                </li>
                                                <li>
                                                    <a href="javascript:;">
                                                        <i class="icon-user"></i> Avaliar
                                                    </a>
                                                </li>
                                            </ul>
                                        </div>
                                    </td>
                                </tr>
                        }
                    </tbody>
                </table>
            </div>
        </div>
        <!-- END EXAMPLE TABLE PORTLET-->
    </div>
</div>
<script src="~/Content/global/scripts/datatable.js" type="text/javascript"></script>
<script src="~/Content/global/plugins/datatables/datatables.min.js" type="text/javascript"></script>
<script src="~/Content/global/plugins/datatables/plugins/bootstrap/datatables.bootstrap.js" type="text/javascript"></script>

<!-- BEGIN PAGE LEVEL SCRIPTS -->
@*<script src="~/Content/pages/scripts/table-datatables-managed.min.js" type="text/javascript"></script>*@
<script>
    $(document).ready(function () {
        $('#sample_1').dataTable({
            destroy: true,
            searching: false,
            ordering: false,
            "bJQueryUI": true,
            "oLanguage": {
                "sProcessing": "Processando...",
                "sLengthMenu": "Mostrar _MENU_ registros",
                "sZeroRecords": "Não foram encontrados resultados",
                "sInfo": "Mostrando de _START_ até _END_ de _TOTAL_ registros",
                "sInfoEmpty": "Mostrando de 0 até 0 de 0 registros",
                "sInfoFiltered": "",
                "sInfoPostFix": "",
                "sSearch": "Buscar:",
                "sUrl": "",
                "oPaginate": {
                    "sFirst": "Primeiro",
                    "sPrevious": "Anterior",
                    "sNext": "Seguinte",
                    "sLast": "Último"
                }
            }
        });
    });
</script>